Add cliq integration
qa-guru/allure-notifications pull request #122
Opened 2022-08-06 12:28 UTC by alirezaafkar

Add Cliq integration.
https://www.zoho.com/cliq/

2023-02-03 14:43 UTC, svasenkov commented
Hi! Can u send screen of test result in messenger?

2023-07-14 17:29 UTC, valfirst requested changes

2023-07-14 17:29 UTC, valfirst commented on src/main/java/guru/qa/allure/notifications/clients/ClientFactory.java
> +import java.util.List;
please avoid such "noisy" changes when only imports order is changed

2025-08-20 14:42 UTC, valfirst commented
Superseded by #382

2025-08-20 14:42 UTC, closed without merging