LoopClient
qa-guru/allure-notifications pull request #215
Opened 2023-09-18 11:20 UTC by slartus

https://developers.loop.ru/integrate/webhooks/incoming/

оттестировано

2023-09-18 11:38 UTC, slartus commented
![image](https://github.com/qa-guru/allure-notifications/assets/1107015/ee877a13-9a62-44fe-ad45-029a9e1d6553)

2023-09-21 08:27 UTC, valfirst requested changes

2023-09-21 08:27 UTC, valfirst commented on README.md
> +    </ul>
```suggestion
    To create your own Loop webhook URL follow these steps.
    <ul>
      <li>Go to main menu of Loop application.</li>
      <li>Click "Integrations".</li>
      <li>Choose "Incoming Webhooks".</li>
      <li>Click "Add Incoming Webhook".</li>
      <li>Fill out the form fields on your choice, make sure to select a channel for messages.</li>
      <li>Click "Save".</li>
      <li>Copy URL of webhook.</li>
    </ul>
```

2023-09-21 08:27 UTC, valfirst commented on README.md
> +    "webHookUrl": ""
```suggestion
    "webhookUrl": ""
```

2023-09-21 08:27 UTC, valfirst commented on src/main/java/guru/qa/allure/notifications/config/loop/Loop.java
> +    private String webHookUrl;
```suggestion
    @SerializedName("webhookUrl")
    private String webhookUrl;
```

2023-09-21 09:49 UTC, valfirst approved these changes

2023-09-21 11:54 UTC, merged