add slack upload flow, up java version to java 11
qa-guru/allure-notifications pull request #292
Opened 2024-08-25 10:20 UTC by Phoenix124

2024-08-26 05:03 UTC, valfirst commented on build.gradle
> +    sourceCompatibility = 11
Allure supports Java 8, it makes sense to keep Java compatibility aligned

2024-08-26 05:06 UTC, valfirst commented on allure-notifications/src/main/resources/log4j2.xml
Please make sure to rebase the branch

2024-08-26 05:21 UTC, valfirst commented on allure-notifications-api/src/main/java/guru/qa/allure/notifications/clients/slack/SlackClient.java
> +        try (CloseableHttpClient client = HttpClients.createDefault()) {
Do not mixup HTTP clients: either use Apache HTTP client or Unirest

2024-08-28 11:39 UTC, Phoenix124 commented
@valfirst review please

2024-09-09 09:43 UTC, valfirst commented on allure-notifications/src/main/resources/log4j2.xml
not fixed, please rebase your branch

2024-09-09 09:44 UTC, valfirst commented on allure-notifications-api/src/main/java/guru/qa/allure/notifications/clients/slack/SlackClient.java
> +        try (CloseableHttpClient client = HttpClients.createDefault()) {
still some parts of Unirest are in use

2024-09-09 09:55 UTC, valfirst requested changes

2024-09-09 09:55 UTC, valfirst commented on allure-notifications-api/src/main/java/guru/qa/allure/notifications/clients/slack/SlackClient.java
> +            log.error("Failed to post message to Slack", e);
wrap into `MessagingException` and re-throw it

2024-09-09 09:55 UTC, valfirst commented on allure-notifications-api/src/main/java/guru/qa/allure/notifications/clients/slack/SlackClient.java
> +    @SneakyThrows
why is it needed?

2024-09-09 09:55 UTC, valfirst commented on allure-notifications-api/src/main/java/guru/qa/allure/notifications/clients/slack/SlackClient.java
> +            log.error("Failed to post message with file to Slack", e);
wrap into `MessagingException` and re-throw it

2024-09-09 09:55 UTC, valfirst commented on allure-notifications-api/src/main/java/guru/qa/allure/notifications/clients/slack/SlackClient.java
> +        return String.format("channel=%s&text=%s", slack.getChat(), proceedMessageData(messageData));
use `UrlEncodedFormEntity` instead

2024-09-09 09:55 UTC, valfirst commented on allure-notifications-api/src/main/java/guru/qa/allure/notifications/clients/slack/SlackClient.java
> +            Thread.sleep(2000);
is there way to check is file processing completed instead of hardcoded wait?

2024-09-21 09:13 UTC, Phoenix124 commented
@valfirst fix review.
Btw, it's needed to use slack chat id instead of chat name.

2024-09-23 07:19 UTC, valfirst commented
@Phoenix124 please rebase the changes against `master` branch

2024-09-24 09:38 UTC, Phoenix124 commented
@valfirst updated from master

2024-09-25 08:59 UTC, valfirst commented on allure-notifications-api/src/main/java/guru/qa/allure/notifications/clients/slack/SlackClient.java
> +                .addHeader(HttpHeaders.CONTENT_TYPE, ContentType.APPLICATION_JSON.getMimeType())
is this header really needed for GET request?

2024-09-25 15:49 UTC, valfirst approved these changes

2024-09-25 15:50 UTC, merged